global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "user-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "user-service:8082"

  - job_name: "material-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "material-service:8082"

  - job_name: "classroom-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "classroom-service:8082"